#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Outline >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Outline=/luci-static/outline
		set luci.main.mediaurlbase=/luci-static/outline
		commit luci
	EOF
fi

exit 0
